name: "all_models_comprehensive"
description: "Comprehensive evaluation of ALL model types - external, local, and baselines"

# All supported model types
models:
    # External OpenRouter models
    -   name: gpt4o
        type: openrouter
        openrouter_id: openai/gpt-4o
        enabled: true

    -   name: claude
        type: openrouter
        openrouter_id: anthropic/claude-3.5-sonnet
        enabled: true

    -   name: qwen_coder
        type: openrouter
        openrouter_id: qwen/qwen-3-coder-32b-instruct
        enabled: true

    -   name: qwen_coder_3
        type: openrouter
        openrouter_id: qwen/qwen3-coder:free
        enabled: true

    -   name: qwen_3_8b
        type: openrouter
        openrouter_id: qwen/qwen3-8b
        enabled: true

    -   name: qwen_3_4b
        type: openrouter
        openrouter_id: qwen/qwen3-4b:free
        enabled: true

    -   name: qwen_3_0.6b
        type: openrouter
        openrouter_id: qwen/qwen3-0.6b-04-28
        enabled: true

    -   name: qwen_3_1.7b
        type: openrouter
        openrouter_id: qwen/qwen3-1.7b
        enabled: true

    -   name: qwen3_next_80b_a3b_instruct
        type: openrouter
        openrouter_id: qwen/qwen3-next-80b-a3b-instruct
        enabled: true

    -   name: qwen3_next_80b_a3b_thinking
        type: openrouter
        openrouter_id: qwen/qwen3-next-80b-a3b-thinking
        enabled: true

    -   name: llama_3.3_8b_instruct
        type: openrouter
        openrouter_id: meta-llama/llama-3.3-8b-instruct:free
        enabled: true

    -   name: gemma_3n_e4b_it
        type: openrouter
        openrouter_id: google/gemma-3n-e4b-it:free
        enabled: true

    -   name: gemma_3n_e2b_it
        type: openrouter
        openrouter_id: google/gemma-3n-e2b-it:free
        enabled: true

    -   name: devstral_small_2505
        type: openrouter
        openrouter_id: mistralai/devstral-small-2505:free
        enabled: true

    -   name: mistral_small_32b_24b_it
        type: openrouter
        openrouter_id: mistralai/mistral-small-3.2-24b-instruct:free
        enabled: true

    -   name: mistral_small_1.1
        type: openrouter
        openrouter_id: mistralai/devstral-small
        enabled: true

    -   name: hunyuan_a13b_instruct
        type: openrouter
        openrouter_id: tencent/hunyuan-a13b-instruct:free
        enabled: true

    -   name: gpt_oss_20b
        type: openrouter
        openrouter_id: openai/gpt-oss-20b:free
        enabled: true

    -   name: qwen3_30b_a3b_thinking_2507
        type: openrouter
        openrouter_id: qwen/qwen3-30b-a3b-thinking-2507
        enabled: true

    -   name: seed_oss_36b_instruct
        type: openrouter
        openrouter_id: bytedance/seed-oss-36b-instruct
        enabled: true

    -   name: nemotron_nano_9b_v2
        type: openrouter
        openrouter_id: nvidia/nemotron-nano-9b-v2:free
        enabled: true

    -   name: ernie_4.5_21b_a3b
        type: openrouter
        openrouter_id: baidu/ernie-4.5-21b-a3b
        enabled: true

    # HuggingFace models (including PEFT)
    -   name: codebert_base
        type: huggingface
        hf_model_id: microsoft/codebert-base-mlm
        use_peft: false
        enabled: false

    -   name: endorlabs_malicious_classifier
        type: huggingface
        hf_base_model_id: microsoft/codebert-base-mlm
        hf_adapter_id: endorlabs/malicious-package-classifier-bert-mal-only
        use_peft: true
        enabled: true

    # Local trained models (will be trained if not exist)
    -   name: icn_model
        type: icn
        enabled: false  # Disable for now until ICN integration is complete

    -   name: amil_model
        type: amil
        enabled: false
        parameters:
            batch_size: 32
            learning_rate: 2e-4
            max_units: 50

    -   name: cpg_model
        type: cpg
        enabled: false
        parameters:
            batch_size: 16
            learning_rate: 1e-4
            hidden_dim: 256
            num_layers: 3

    -   name: neobert_model
        type: neobert
        enabled: false
        parameters:
            batch_size: 8
            learning_rate: 5e-5
            max_length: 512
            pooling_strategy: attention

    # Baseline models
    -   name: heuristic_baseline
        type: baseline
        parameters:
            baseline_type: heuristic

    -   name: random_baseline
        type: baseline
        parameters:
            baseline_type: random

# Prompt strategies (for external models only)
prompts:
    zero_shot: true
    few_shot: true
    reasoning: true
    file_by_file: false  # Expensive

    # Custom prompt overrides (optional)
    custom_prompts:
        # Override zero-shot prompt
        zero_shot: |
            You are a security expert analyzing package code for malicious behavior.

            Code to analyze:
            ```
            {code_content}
            ```

            Focus on these red flags:
            - Cryptocurrency mining operations
            - Data harvesting (browser data, SSH keys, environment variables)
            - Remote code execution capabilities
            - Suspicious network communication
            - Installation hooks that download additional payloads

            Classification: [MALICIOUS/BENIGN]
            Confidence: [0.0-1.0]
            Reasoning: [Brief explanation]

        # Override few-shot prompt with better examples
        few_shot: |
            You are a security expert. Learn from these examples, then analyze the target package.

            {examples}

            Now analyze this package using the same methodology:
            ```
            {code_content}
            ```

            Key indicators to check:
            - Network requests to suspicious domains
            - File system access patterns
            - Process execution attempts
            - Cryptocurrency mining signatures
            - Data collection behaviors
            - Obfuscation techniques

            Provide your analysis in the same format:
            Classification: [MALICIOUS/BENIGN]
            Confidence: [0.0-1.0]
            Indicators: [List key findings]
            Reasoning: [Detailed explanation]

        # Override reasoning prompt for more detailed analysis
        reasoning: |
            Analyze this package code using advanced threat detection methodology:

            Code:
            ```
            {code_content}
            ```

            Step-by-step analysis:
            1. **Static Analysis**: Examine code structure and imports
            2. **Behavioral Analysis**: Identify system interactions
            3. **Network Analysis**: Check for external communications
            4. **Persistence Analysis**: Look for installation hooks
            5. **Obfuscation Detection**: Identify evasion techniques
            6. **Risk Scoring**: Calculate threat level

            Provide detailed analysis for each step, then conclude with:
            Classification: [MALICIOUS/BENIGN]
            Confidence: [0.0-1.0]
            Final Risk Score: [1-10]

        # Override file-by-file prompt for granular analysis
        file_by_file: |
            Analyze this individual file from a package for malicious behavior.

            File: {file_path}
            File Type: {file_type}
            Package Context: {package_name}

            Code:
            ```
            {file_content}
            ```

            File-specific analysis checklist:
            - **Purpose**: What is this file supposed to do?
            - **Suspicious Imports**: Unusual or dangerous libraries
            - **Network Activity**: External connections or data transmission
            - **File Operations**: Reading/writing sensitive files
            - **Process Control**: System commands or subprocess calls
            - **Obfuscation**: Encoded strings, dynamic imports, eval usage
            - **Installation Hooks**: Package installation behavior
            - **Context Clues**: How does this fit with other package files?

            File Risk Assessment:
            Risk Level: [LOW/MEDIUM/HIGH/CRITICAL]
            Confidence: [0.0-1.0]
            Malicious Indicators: [List specific findings]
            Benign Indicators: [List legitimate functionality]
            Recommendation: [ALLOW/QUARANTINE/BLOCK]
            Reasoning: [Detailed file-specific analysis]

# Data configuration
data:
    max_samples_per_category: 30  # Moderate for comprehensive test
    use_cached_data: true

# Execution settings
execution:
    cost_limit_usd: 100.0  # External models cost
    max_concurrent_requests: 2

# Output settings
output:
    output_directory: "all_models_results"
    save_visualizations: true
    generate_markdown_report: true

# Statistical analysis
enable_statistical_testing: true
statistical_significance_level: 0.05