api_keys: {}
data:
  data_path: null
  include_categories:
  - benign
  - compromised_lib
  - malicious_intent
  max_samples_per_category: 50
  test_split_ratio: 0.3
  use_cached_data: true
description: Comprehensive evaluation of all external models with multiple prompts
enable_statistical_testing: true
execution:
  cost_limit_usd: 40.0
  delay_between_requests: 0.1
  max_concurrent_requests: 2
  max_retries: 3
  requests_per_minute: 60
  retry_failed: true
  timeout_seconds: 120
models:
- enabled: true
  hf_model_id: null
  model_path: null
  name: gpt4o
  openrouter_id: openai/gpt-4o
  parameters: {}
  type: openrouter
- enabled: true
  hf_model_id: null
  model_path: null
  name: o1_preview
  openrouter_id: openai/o1-preview
  parameters: {}
  type: openrouter
- enabled: true
  hf_model_id: null
  model_path: null
  name: claude
  openrouter_id: anthropic/claude-3.5-sonnet
  parameters: {}
  type: openrouter
- enabled: true
  hf_model_id: null
  model_path: null
  name: gemini_pro
  openrouter_id: google/gemini-pro-1.5
  parameters: {}
  type: openrouter
- enabled: true
  hf_model_id: null
  model_path: null
  name: qwen_coder
  openrouter_id: qwen/qwen-3-coder-32b-instruct
  parameters: {}
  type: openrouter
- enabled: true
  hf_model_id: null
  model_path: null
  name: deepseek
  openrouter_id: deepseek/deepseek-coder-v2-instruct
  parameters: {}
  type: openrouter
- enabled: true
  hf_model_id: null
  model_path: null
  name: llama33
  openrouter_id: meta-llama/llama-3.3-70b-instruct
  parameters: {}
  type: openrouter
name: external_models_comprehensive
output:
  create_heatmaps: true
  create_ranking_charts: true
  create_scatter_plots: true
  generate_csv_export: false
  generate_json_summary: true
  generate_markdown_report: true
  output_directory: external_comprehensive_results
  save_analysis: true
  save_raw_results: true
  save_visualizations: true
prompts:
  custom_prompts: {}
  few_shot: true
  few_shot_examples_count: 3
  file_by_file: false
  max_tokens:
    few_shot: 1500
    file_by_file: 800
    reasoning: 2000
    zero_shot: 1000
  reasoning: true
  zero_shot: true
statistical_significance_level: 0.05
